
services:
  user-service:
    build: ./user_service
    ports:
      - "5001:5000"
    networks:
      - bookstore-net

  book-service:
    build: ./book_service
    ports:
      - "5002:5000"
    networks:
      - bookstore-net

  order-service:
    build: ./order_service
    ports:
      - "5003:5000"
    networks:
      - bookstore-net
    depends_on:
      - user-service

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - bookstore-net
    depends_on:
      - user-service
      - book-service
      - order-service

networks:
  bookstore-net:
