services:
  user-service:
    build: ./user_service
    ports:
      - "5001:5000"

  book-service:
    build: ./book_service
    ports:
      - "5002:5000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  
  order-service:
    build: ./order_service
    ports:
      - "5003:5000"


