name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.2
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r user_service/requirements.txt
        pip install -r book_service/requirements.txt
        pip install -r order_service/requirements.txt

    - name: Run User Service Tests
      run: |
        PYTHONPATH=. pytest user_service/tests/

    - name: Run Book Service Tests
      run: |
        PYTHONPATH=. pytest book_service/tests/

    - name: Build Docker images
      run: |
        docker build -t user-service ./user_service
        docker build -t book-service ./book_service
        docker build -t order-service ./order_service

    # Optional deployment step
    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl apply -f k8s/
